# docker-compose.yaml
version: "3.7"

services:
  go-url:
    container_name: go-url
    image: thisk8brd/go-url:dev
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    ports:
      - "5000:5000"
      - "2345:2345"
    networks:
      - go-url-network

  go-url-db:
    container_name: go-url-db
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - go-url-network

volumes:
  postgres-db:

networks:
  go-url-network:
    name: go-url-network
    