name: run-commands
run-name: ${{ github.actor }} is trying to integrate
on: [push]
jobs:
  autograde-commands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run install
        run: ./run install
      - name: Run build
        run: ./run build
      - name: Run Test
        run: ./run test
      - name: set env
        run: echo "ABSFILEPATH=$(readlink -f test/urls_file.txt)" >> $GITHUB_ENV
      - name: test env
        run: echo $ABSFILEPATH