name: run-commands
run-name: ${{ github.actor }} is trying to integrate
on: [push]
jobs:
  autograde-commands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run autograde script
        run: |
          go build -o run
          ./run install
          ./run build
          ./run test
          ./run /Users/mmcho/OneDrive - purdue.edu/ECE 461/Part 1/461_1_23/test/durls_file.txt
        shell: bash