name: run-commands
run-name: ${{ github.actor }} is trying to integrate
on: [push]
jobs:
  autograde-commands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run autograde script
        run: |
          go build -o run
          ./run install
          ./run build
          ./run test
          ABSFILEPATH=$(readlink -f test/urls_file.txt)
          ./run "${ABSFILEPATH}"
        shell: bash