name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [pull_request]
jobs:
  check-bats-version:
    steps:
      - name: Run autograde script
        run: ./.github/workflows/run.sh
        shell: bash