name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  autograde-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Run autograde script
        run: echo -n "testtesttest"
        shell: bash