name: run-commands
run-name: ${{ github.actor }} is trying to integrate
on: [push]
jobs:
  autograde-commands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run install
        run: ./run install
      - name: Run build
        run: ./run build
      - name: List items
        run: ls -la
      - name: Run Test
        run: ./run test
      - name: Run URL_FILE
        run:
          ABSFILEPATH=$(readlink -f test/urls_file.txt
          ./run "${ABSFILEPATH}"
        shell: bash