name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  autograde-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Run autograde script
        run: 461_1_23/.github/workflows/run.sh
        shell: bash